package com.school.pojo;

import java.util.Date;
import java.util.List;



public class Order {
	
	 private List<OrderDetail> orderDetailList;//订单明细列表
	    

	    public List<OrderDetail> getOrderDetailList() {
			return orderDetailList;
		}

		public void setOrderDetailList(List<OrderDetail> orderDetailList) {
			this.orderDetailList = orderDetailList;
		}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer userid;
   

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.loginName
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userAddress
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private String useraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.createTime
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.cost
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Float cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.serialNumber
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private String serialnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userId
     *
     * @return the value of order.userId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userId
     *
     * @param userid the value for order.userId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.loginName
     *
     * @return the value of order.loginName
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.loginName
     *
     * @param loginname the value for order.loginName
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userAddress
     *
     * @return the value of order.userAddress
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userAddress
     *
     * @param useraddress the value for order.userAddress
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress == null ? null : useraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.createTime
     *
     * @return the value of order.createTime
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.createTime
     *
     * @param createtime the value for order.createTime
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.cost
     *
     * @return the value of order.cost
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Float getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.cost
     *
     * @param cost the value for order.cost
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setCost(Float cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.serialNumber
     *
     * @return the value of order.serialNumber
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public String getSerialnumber() {
        return serialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.serialNumber
     *
     * @param serialnumber the value for order.serialNumber
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber == null ? null : serialnumber.trim();
    }
}