package com.school.pojo;



public class OrderDetail {
	
	private Product product;//商品
	
    public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.orderId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.productId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.quantity
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.cost
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Float cost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.id
     *
     * @return the value of order_detail.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.id
     *
     * @param id the value for order_detail.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.orderId
     *
     * @return the value of order_detail.orderId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.orderId
     *
     * @param orderid the value for order_detail.orderId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.productId
     *
     * @return the value of order_detail.productId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.productId
     *
     * @param productid the value for order_detail.productId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.quantity
     *
     * @return the value of order_detail.quantity
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.quantity
     *
     * @param quantity the value for order_detail.quantity
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.cost
     *
     * @return the value of order_detail.cost
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Float getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.cost
     *
     * @param cost the value for order_detail.cost
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setCost(Float cost) {
        this.cost = cost;
    }
}