package com.school.pojo;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.categoryLevel1Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer categorylevel1id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.categoryLevel2Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer categorylevel2id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.categoryLevel3Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer categorylevel3id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.fileName
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.isDelete
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.categoryLevel1Id
     *
     * @return the value of product.categoryLevel1Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getCategorylevel1id() {
        return categorylevel1id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.categoryLevel1Id
     *
     * @param categorylevel1id the value for product.categoryLevel1Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setCategorylevel1id(Integer categorylevel1id) {
        this.categorylevel1id = categorylevel1id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.categoryLevel2Id
     *
     * @return the value of product.categoryLevel2Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getCategorylevel2id() {
        return categorylevel2id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.categoryLevel2Id
     *
     * @param categorylevel2id the value for product.categoryLevel2Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setCategorylevel2id(Integer categorylevel2id) {
        this.categorylevel2id = categorylevel2id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.categoryLevel3Id
     *
     * @return the value of product.categoryLevel3Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getCategorylevel3id() {
        return categorylevel3id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.categoryLevel3Id
     *
     * @param categorylevel3id the value for product.categoryLevel3Id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setCategorylevel3id(Integer categorylevel3id) {
        this.categorylevel3id = categorylevel3id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.fileName
     *
     * @return the value of product.fileName
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.fileName
     *
     * @param filename the value for product.fileName
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.isDelete
     *
     * @return the value of product.isDelete
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.isDelete
     *
     * @param isdelete the value for product.isDelete
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}