package com.school.pojo;

import java.util.Date;

public class UserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.userId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.createTime
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.isDefault
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private Integer isdefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.remark
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.userId
     *
     * @return the value of user_address.userId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.userId
     *
     * @param userid the value for user_address.userId
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address
     *
     * @return the value of user_address.address
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address
     *
     * @param address the value for user_address.address
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.createTime
     *
     * @return the value of user_address.createTime
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.createTime
     *
     * @param createtime the value for user_address.createTime
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.isDefault
     *
     * @return the value of user_address.isDefault
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public Integer getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.isDefault
     *
     * @param isdefault the value for user_address.isDefault
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setIsdefault(Integer isdefault) {
        this.isdefault = isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.remark
     *
     * @return the value of user_address.remark
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.remark
     *
     * @param remark the value for user_address.remark
     *
     * @mbggenerated Sun Jul 07 17:44:58 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}